name: 'Node - Setup and install dependencies'

inputs:
  node-version:
    description: 'The Node version that should be used for the build'
    required: true
    default: '16.x'
  
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: List working directory
      run: ls -la
      shell: bash
    - name: Install dependencies
      run: npm ci
      shell: bash
