name: 'Setup and install dependencies'

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  node-version:
    description: 'The Node version that should be used for the build'
    required: true
    default: '22.x'
  registry-url:
    description: 'Registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.'
    required: false
    default: ''
  registry-token:
    description: 'The token to use for authentication with the registry.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
        registry-url: ${{ inputs.registry-url }}
    - name: Install dependencies
      env:
        NODE_AUTH_TOKEN: ${{ inputs.registry-token }}
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
      shell: bash
