name: 'Node - Lint code'

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  lint-command:
    description: 'The lint command'
    required: true
    default: 'npm run lint'
  
runs:
  using: "composite"
  steps:
    - name: Lint code
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.lint-command }}
      shell: bash
