name: 'Configure an organization on GitHub NPM registry'

inputs:
  organization:
    description: 'The NPM organization that should point to GitHub'
    required: true
    default: 'aboutbits'

runs:
  using: 'composite'
  steps:
    - name: Configure access for GitHub NPM registry
      run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
      shell: bash
    - name: Point organization to GitHub NPM registry
      run: echo "@${{ inputs.organization }}:registry=https://npm.pkg.github.com" >> ~/.npmrc
      shell: bash