name: 'Setup'

inputs:
  node-version:
    description: 'The Node version that should be used for the build'
    required: true
    default: '16.x'
  registry-url:
    description: 'Registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
